timezone: Asia/Ho_Chi_Minh

wandb:
  project: person-reid-v2
  entity: hiennguyen9874

optimizer:
  name: adamW
  lr: 3.5e-4
  weight_decay: 0.0005
  bias_lr_factor: null
  bias_weight_decay: null
  norm_weight_decay: null
  overrides: {}

  adam:
    beta1: 0.9
    beta2: 0.99
    amsgrad: False

  sgd:
    momentum: 0.937
    dampening: 0
    nesterov: True

  adamW:
    beta1: 0.9
    beta2: 0.999

freeze:
  enable: False
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: False
  name: MultiStepLR
  start: 1

  WarmupMultiStepLR:
    steps: [40, 90]
    gamma: 0.1
    warmup_factor: 0.01
    warmup_iters: 10
    warmup_method: linear

  ReduceLROnPlateau:
    factor: 0.1
    patience: 10
    min_lr: 1.0e-7

  MultiStepLR:
    steps: [40, 70]
    gamma: 0.1

  WarmupCosineAnnealingLR:
    max_iters: 120
    delay_iters: 30
    eta_min_lr: 7.0e-7
    warmup_factor: 0.01
    warmup_iters: 10
    warmup_method: linear

  CosineAnnealingLR:
    max_iters: 120
    eta_min_lr: 7.0e-7

  # OneCycleLR:
  #   epochs: 120
  #   max_lr: 0.01
  #   div_factor: 25
  #   anneal_strategy: cos # or linear

iters_to_accumulate: 1

ema:
  enable: False
  decay: 0.9998

clip_grad_norm_:
  enable: False
  max_norm: 10.0

trainer:
  epochs: 120
  amp: True
